### ISSUE TITLE
<Fit />'s child does not have absolute position. You should apply `position: absolute` to it.

### ISSUE THREAD

**Issue by NickersWeb** [wojtekmaj/react-datetime-picker#137]
Keep getting this warning in the console log from this component

**Comment by jtieu-r7** [comment]
Also running into this, any updates?

**Comment by NickersWeb** [comment]
Nothing on my end

**Comment by efleurine** [comment]
I got this `react_devtools_backend.js:4049 <Fit />'s child needed to have its height decreased to 99px.`
but it happens only when the developer tools is open at the bottom and if I move it in a way there is more space or if the developer console is moved to the side. it does not show up. I assume it should be connected to the lesser space that happens when the developer tools is open.

**Comment by jasonelliott** [comment]
I'm getting this too

**Comment by ev3nst** [comment]
````css
.react-datetime-picker__calendar--open,
.react-datetime-picker__calendar--closed,
.react-datetime-picker__clock--open,
.react-datetime-picker__clock--closed {
	position: absolute;
}
````
